import {settings,saveSettings,tags,saveTags} from './storage.js';import {supported,scan,writeName} from './nfc.js';import {mailBody,mailto} from './mail.js';
const $=s=>document.querySelector(s);let prefs=settings(), registry=tags(), workers=[], pendingTime=null, toastTimer;
const now=()=>new Intl.DateTimeFormat('fr-FR',{hour:'2-digit',minute:'2-digit'}).format(new Date());
const initials=n=>n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500)}
function returnFor(w){return w.specific|| (w.full?prefs.endday:prefs.midday)}
function render(){const list=$('#workerList');$('#countLabel').textContent=`${workers.length} personne${workers.length>1?'s':''} scannée${workers.length>1?'s':''}`;$('#countPill').textContent=workers.length;$('#sendTop').disabled=$('#sendBottom').disabled=!workers.length;if(!workers.length){list.innerHTML='<div class="empty-state"><span aria-hidden="true">◌</span><p>Votre équipe apparaîtra ici<br><small>Commencez par scanner un badge.</small></p></div>';return}list.innerHTML=workers.map((w,i)=>`<article class="worker-card"><div class="worker-top"><div class="avatar" aria-hidden="true">${initials(w.name)}</div><strong class="worker-name">${escapeHtml(w.name)}</strong><button class="edit-btn" data-edit="${i}" aria-label="Définir une heure de retour pour ${escapeHtml(w.name)}">✎</button></div><div class="worker-meta"><span>Scan à <strong>${w.scan}</strong></span><label class="toggle-wrap"><span>Journée complète</span><input class="toggle" type="checkbox" data-toggle="${i}" ${w.full?'checked':''} aria-label="Journée complète pour ${escapeHtml(w.name)}"></label><span class="return-time">Retour <strong>${returnFor(w)}</strong></span></div></article>`).join('')}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function add(name){name=name.trim();if(!name)return;workers.push({name,scan:now(),full:false,specific:null});render();notify(`${name} ajouté·e au pointage`)}
function openFallback(reason=''){ $('#fallbackReason').textContent=reason||'La saisie manuelle reste disponible sur tous les appareils.';$('#manualName').value='';$('#fallbackDialog').showModal();setTimeout(()=>$('#manualName').focus(),50)}
async function startScan(){if(!supported()){openFallback('Web NFC n’est pas pris en charge ici. Saisissez le nom manuellement pour continuer.');return}try{await scan(name=>{const match=registry.find(t=>t.name.toLowerCase()===name.toLowerCase());add(match?.name||name);notify('Badge NFC lu');}) ;notify('Approchez un badge NFC du téléphone…')}catch(e){openFallback(e.message)}}
function renderTags(){const el=$('#tagList');el.innerHTML=registry.length?registry.map((t,i)=>`<div class="tag-row"><span>${escapeHtml(t.name)}</span><div class="tag-actions"><button data-rename="${i}" aria-label="Renommer ${escapeHtml(t.name)}">✎</button><button class="delete" data-delete="${i}" aria-label="Supprimer ${escapeHtml(t.name)}">⌫</button></div></div>`).join(''):'<p class="muted">Aucun badge enregistré.</p>'}
function send(){const body=mailBody(workers);console.info('MAIL_PREVIEW\n'+body);window.location.href=mailto(workers);notify('Récapitulatif préparé dans votre messagerie')}
$('#todayLabel').textContent=new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long'}).format(new Date());$('#scanHint').textContent=supported()?'Web NFC disponible · saisie manuelle possible':'NFC indisponible · saisie manuelle disponible';$('#scanBtn').onclick=startScan;$('#manualAdd').onclick=e=>{e.preventDefault();add($('#manualName').value);$('#fallbackDialog').close()};$('#sendTop').onclick=$('#sendBottom').onclick=send;$('#settingsBtn').onclick=()=>{$('#settingsPanel').classList.add('open');$('#settingsPanel').setAttribute('aria-hidden','false');$('#midday').value=prefs.midday;$('#endday').value=prefs.endday;renderTags()};$('#closeSettings').onclick=()=>{$('#settingsPanel').classList.remove('open');$('#settingsPanel').setAttribute('aria-hidden','true')};$('#saveSettings').onclick=()=>{prefs={midday:$('#midday').value||'12:00',endday:$('#endday').value||'17:00'};saveSettings(prefs);render();notify('Horaires enregistrés')};$('#enrollBtn').onclick=async()=>{const name=prompt('Nom Prénom à inscrire');if(!name?.trim())return;try{await writeName(name.trim());registry.push({name:name.trim()});saveTags(registry);renderTags();notify('Tag inscrit et enregistré')}catch(e){notify(e.message+' Utilisez un appareil Android compatible.')}};
$('#workerList').onclick=e=>{const edit=e.target.closest('[data-edit]');const toggle=e.target.closest('[data-toggle]');if(edit){pendingTime=+edit.dataset.edit;$('#timeDialogTitle').textContent=`Retour de ${workers[pendingTime].name}`;$('#specificTime').value=workers[pendingTime].specific||returnFor(workers[pendingTime]);$('#timeDialog').showModal();setTimeout(()=>$('#specificTime').focus(),50)}if(toggle){workers[+toggle.dataset.toggle].full=toggle.checked;render()}};$('#saveTime').onclick=e=>{e.preventDefault();if(pendingTime!==null){workers[pendingTime].specific=$('#specificTime').value;render();$('#timeDialog').close();notify('Heure spécifique enregistrée');pendingTime=null}};$('#tagList').onclick=e=>{const del=e.target.closest('[data-delete]'),ren=e.target.closest('[data-rename]');if(del){registry.splice(+del.dataset.delete,1);saveTags(registry);renderTags();notify('Badge supprimé')}if(ren){const i=+ren.dataset.rename,n=prompt('Nouveau nom',registry[i].name);if(n?.trim()){registry[i].name=n.trim();saveTags(registry);renderTags()}}};
if('serviceWorker' in navigator && location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('SW non enregistré',e));render();
